# Generated by Django 3.1.13 on 2021-09-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_id',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Country ID'),
        ),
    ]
