# Generated by Django 3.1.13 on 2021-09-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_country_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='call_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='population',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='sub_region',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
