# Generated by Django 3.1.13 on 2021-09-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210905_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
