# Generated by Django 3.1.13 on 2021-09-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_auto_20210905_1730'),
        ('core', '0008_auto_20210905_1620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
