# Generated by Django 3.1.13 on 2021-09-04 09:44

import autobuyfast.career.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Career Title')),
                ('position', models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Career Position')),
                ('type', models.CharField(blank=True, choices=[('office', 'Office'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='office', max_length=10, null=True, verbose_name='Career Type')),
                ('slug', models.SlugField(blank=True, max_length=700, null=True, unique=True)),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Career Details and Requirements')),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=100, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Career',
                'verbose_name_plural': 'Careers',
                'ordering': ['-created', '-modified'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CareerApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cv', models.FileField(null=True, upload_to=autobuyfast.career.models.cv_file_path, verbose_name='Upload Your CV')),
                ('name', models.CharField(max_length=500, null=True, verbose_name='Your Fullname')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Your Email')),
                ('address', models.CharField(max_length=700, null=True, verbose_name='Your Residential Address')),
                ('linkedin', models.URLField(null=True, verbose_name='Your Linkedin Profile')),
                ('facebook', models.URLField(null=True, verbose_name='Your Facebook Profile')),
                ('twitter', models.URLField(null=True, verbose_name='Your Twitter Profile')),
                ('career', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='career.career')),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country')),
            ],
            options={
                'verbose_name': 'Career Application',
                'verbose_name_plural': 'Career Applications',
                'ordering': ['-created', '-modified'],
                'managed': True,
            },
        ),
    ]
