# Generated by Django 3.1.13 on 2021-09-05 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerapply',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='countries_plus.country'),
        ),
    ]
