# Generated by Django 3.1.13 on 2021-07-21 21:16

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('car_image', models.URLField(blank=True, max_length=700, null=True, unique=True, verbose_name='Car Image Url')),
                ('car_stock', models.CharField(blank=True, default='used', max_length=700, null=True, verbose_name='Used or New Stock')),
                ('car_year', models.CharField(blank=True, default='2001', max_length=700, null=True, verbose_name='Production Year')),
                ('car_title', models.CharField(blank=True, max_length=700, null=True, unique=True, verbose_name='Car Title')),
                ('car_url', models.CharField(blank=True, max_length=700, null=True, unique=True, verbose_name='Car Detail Link')),
                ('car_mileage', models.CharField(blank=True, default='car mileage', max_length=20, null=True, verbose_name='Car Mileage')),
                ('car_price', models.CharField(blank=True, default='0.00', max_length=700, null=True, verbose_name='Car Price')),
                ('car_history', models.URLField(blank=True, max_length=700, null=True, unique=True, verbose_name='Car History Link')),
                ('car_dealer_name', models.CharField(blank=True, default='car dealer name', max_length=700, null=True, verbose_name='Car Dealer')),
                ('car_dealer_rating', models.CharField(blank=True, default='4', max_length=6, null=True, verbose_name='Car Dealer Rating')),
                ('car_dealer_reviews', models.CharField(blank=True, default='200 Reviews', max_length=25, null=True, verbose_name='Car Dealer No Reviews')),
                ('car_dealer_phone', models.CharField(blank=True, default='+1864756473547', max_length=16, null=True, verbose_name='Car Dealer Phone Number')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'cars',
                'ordering': ['-created', '-modified', '-car_year'],
                'managed': True,
            },
        ),
    ]
