# Generated by Django 3.1.13 on 2021-07-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosearch',
            name='car_image',
            field=models.URLField(blank=True, max_length=700, null=True, verbose_name='Car Image Url'),
        ),
    ]
