# Generated by Django 3.1.13 on 2021-07-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210721_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosearch',
            name='car_title',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Car Title'),
        ),
    ]
