# Generated by Django 3.1.13 on 2021-07-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210721_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosearch',
            name='car_mileage',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=40, null=True, verbose_name='Car Mileage'),
        ),
        migrations.AlterField(
            model_name='autosearch',
            name='car_price',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=40, null=True, verbose_name='Car Price'),
        ),
        migrations.AlterField(
            model_name='autosearch',
            name='car_stock',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Used or New Stock'),
        ),
        migrations.AlterField(
            model_name='autosearch',
            name='car_year',
            field=models.PositiveSmallIntegerField(blank=True, max_length=7, null=True, verbose_name='Production Year'),
        ),
    ]
