# Generated by Django 3.1.13 on 2021-07-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20210722_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosearch',
            name='car_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Production Year'),
        ),
    ]
