# Generated by Django 3.1.13 on 2021-07-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20210722_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosearch',
            name='car_history',
            field=models.URLField(blank=True, max_length=700, null=True, verbose_name='Car History Link'),
        ),
    ]
