# Generated by Django 3.1.13 on 2021-07-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20210722_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosearch',
            name='car_image',
            field=models.URLField(blank=True, max_length=700, null=True, unique=True, verbose_name='Car Image Url'),
        ),
    ]
