# Generated by Django 3.1.13 on 2021-08-11 07:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20210723_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=500, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Car Body',
                'verbose_name_plural': 'Car Bodys',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Seating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=500, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Car Seating',
                'verbose_name_plural': 'Car Seatings',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='autosearch',
            name='car_image',
        ),
        migrations.AddField(
            model_name='autosearch',
            name='car_def_image',
            field=models.URLField(blank=True, max_length=700, null=True, verbose_name='Car Default Image'),
        ),
        migrations.AddField(
            model_name='autosearch',
            name='car_drive_train',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Car Drive Train'),
        ),
        migrations.AddField(
            model_name='autosearch',
            name='car_engine',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Car Engine'),
        ),
        migrations.AddField(
            model_name='autosearch',
            name='car_ext_color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Car Ext Color'),
        ),
        migrations.AddField(
            model_name='autosearch',
            name='car_fuel_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Car Fuel Type'),
        ),
        migrations.AddField(
            model_name='autosearch',
            name='car_int_color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Car Int Color'),
        ),
        migrations.AddField(
            model_name='autosearch',
            name='car_transmission',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Car Transmission'),
        ),
        migrations.AddField(
            model_name='autosearch',
            name='car_vin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Car VIN'),
        ),
        migrations.AddField(
            model_name='autosearch',
            name='seller_note',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Seller Note'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', models.URLField(blank=True, max_length=1000, null=True, unique=True, verbose_name='Car Image Url')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.autosearch')),
            ],
            options={
                'verbose_name': 'Car Files',
                'verbose_name_plural': 'Car Files',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='autosearch',
            name='car_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carbody', to='cars.body'),
        ),
        migrations.AddField(
            model_name='autosearch',
            name='car_seating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carseating', to='cars.seating'),
        ),
    ]
