# Generated by Django 3.1.13 on 2021-08-11 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_auto_20210811_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='cars.autosearch'),
        ),
    ]
