# Generated by Django 3.1.13 on 2021-08-11 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0011_auto_20210811_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autosearch',
            name='car_body',
        ),
        migrations.RemoveField(
            model_name='autosearch',
            name='car_seating',
        ),
        migrations.AddField(
            model_name='autosearch',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='autosearch',
            name='car_url',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Car Detail Link'),
        ),
        migrations.AlterField(
            model_name='autosearch',
            name='car_vin',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Car VIN'),
        ),
        migrations.AlterField(
            model_name='autosearch',
            name='seller_note',
            field=tinymce.models.HTMLField(blank=True, default='From https://cars.com, follow the link to see their reviews and comments on this car', null=True, verbose_name='Seller Note'),
        ),
    ]
