# Generated by Django 3.1.13 on 2021-08-11 13:56

import autobuyfast.cars.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_auto_20210811_1124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Body',
        ),
        migrations.DeleteModel(
            name='Seating',
        ),
        migrations.AddField(
            model_name='autosearch',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='autosearch',
            name='status',
            field=models.CharField(blank=True, choices=[('unpublished', 'unpublished'), ('published', 'published')], default='published', max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='Size 400px x 328px', keep_meta=True, null=True, quality=75, size=[400, 328], upload_to=autobuyfast.cars.models.post_image, verbose_name='Upload Car Image'),
        ),
    ]
