# Generated by Django 3.1.13 on 2021-08-11 16:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_auto_20210811_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('stock', models.CharField(blank=True, max_length=700, null=True, verbose_name='Used or New Stock')),
            ],
            options={
                'verbose_name': 'Car Stock Type',
                'verbose_name_plural': 'Car Stock Types',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Production Year')),
            ],
            options={
                'verbose_name': 'Car Year',
                'verbose_name_plural': 'Car Years',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='autosearch',
            name='car_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_stock', to='cars.stock'),
        ),
        migrations.AlterField(
            model_name='autosearch',
            name='car_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_year', to='cars.year'),
        ),
    ]
