# Generated by Django 3.1.13 on 2021-08-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_auto_20210812_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosearch',
            name='car_stock',
            field=models.CharField(blank=True, choices=[('Used', 'Used'), ('Ac Certified', 'ac'), ('Acura Certified', 'acura'), ('Alfa Romeo  Certified', 'alfa romeo'), ('Allard Certified', 'allard'), ('Amc Certified', 'amc'), ('Am General Certified', 'am general'), ('American Motors Certified', 'american motors'), ('Ariel Certified', 'ariel'), ('Aston Martin Certified', 'aston martin'), ('Auburn Certified', 'auburn'), ('Audi Certified', 'audi'), ('Austin Certified', 'austin'), ('Austin Healey Certified', 'austin healey'), ('Avantimotors Certified', 'avantimotors'), ('Bentley Certified', 'bentley'), ('BMW Certified', 'bmw'), ('Bugatti Certified', 'bugatti'), ('Buick Certified', 'buick'), ('Cadillac Certified', 'cadillac'), ('Checker Certified', 'checker'), ('Chevrolet Certified', 'chevrolet'), ('Chrysler Certified', 'chrysler'), ('Citroen Certified', 'citroen'), ('Daewoo Certified', 'daewoo'), ('Daihatsu Certified', 'daihatsu'), ('Datsun Certified', 'datsun'), ('Delahaye Certified', 'delahaye'), ('Delorean Certified', 'delorean'), ('Desoto Certified', 'desoto'), ('Detomaso Certified', 'detomaso'), ('Dodge Certified', 'dodge'), ('Eagle Certified', 'eagle'), ('Edsel Certified', 'edsel'), ('Essex Certified', 'essex'), ('Ferrari Certified', 'ferrari'), ('Fiat Certified', 'fiat'), ('Fisker Certified', 'fisker'), ('Ford Certified', 'ford'), ('Franklin Certified', 'franklin'), ('Freightliner Certified', 'freightliner'), ('Genesis Certified', 'genesis'), ('GEO Certified', 'geo'), ('GMC Certified', 'gmc'), ('Hino Certified', 'hino'), ('Honda Certified', 'honda'), ('Hudson Certified', 'hudson'), ('Hummer Certified', 'hummer'), ('Hupmobile Certified', 'hupmobile'), ('Hyundai Certified', 'hyundai'), ('Infiniti Certified', 'infiniti'), ('International Certified', 'international'), ('Intlharvester Certified', 'intlharvester'), ('Isuzu Certified', 'isuzu'), ('Jaguar Certified', 'jaguar'), ('Jeep Certified', 'jeep'), ('Jensen Certified', 'jensen'), ('Kaiser Certified', 'kaiser'), ('Karma Certified', 'karma'), ('Kia Certified', 'kia'), ('Koenigsegg Certified', 'koenigsegg'), ('Lamborghini Certified', 'lamborghini'), ('Lancia Certified', 'lancia'), ('Land Rover Certified', 'land rover'), ('Lasalle Certified', 'lasalle'), ('Lexus Certified', 'lexus'), ('Lincoln Certified', 'lincoln'), ('Lotus Certified', 'lotus'), ('Maserati Certified', 'maserati'), ('Maybach Certified', 'maybach'), ('Mazda Certified', 'mazda'), ('Mclaren Certified', 'mclaren'), ('Mercedes Benz Certified', 'mercedes benz'), ('Mercury Certified', 'mercury'), ('Merkur Certified', 'merkur'), ('MG Certified', 'mg'), ('Mini Certified', 'mini'), ('Mitsubishi Certified', 'mitsubishi'), ('Morgan Certified', 'morgan'), ('Morris Certified', 'morris'), ('Nash Certified', 'nash'), ('Nissan Certified', 'nissan'), ('Oldsmobile Certified', 'oldsmobile'), ('Opel Certified', 'opel'), ('Packard Certified', 'packard'), ('Pagani Certified', 'pagani'), ('Panoz Certified', 'panoz'), ('Peugeot Certified', 'peugeot'), ('Plymouth Certified', 'plymouth'), ('Polestar Certified', 'polestar'), ('Pontiac Certified', 'pontiac'), ('Porsche Certified', 'porsche'), ('Qvale Certified', 'qvale'), ('Ram Certified', 'ram'), ('Renault Certified', 'renault'), ('Rolls Royce Certified', 'rollsroyce'), ('Rover', 'rover'), ('Saab Certified', 'saab'), ('Saleen Certified', 'saleen'), ('Saturn Certified', 'saturn'), ('Scion Certified', 'scion'), ('Ehelby Certified', 'shelby'), ('Smart Certified', 'smart'), ('Spyker Certified', 'spyker'), ('Sterling Certified', 'sterling'), ('Studebaker Certified', 'studebaker'), ('Subaru Certified', 'subaru'), ('Sunbeam Certified', 'sunbeam'), ('Suzuki Certified', 'suzuki'), ('Tesla Certified', 'tesla'), ('Toyota Certified', 'toyota'), ('Triumph Certified', 'triumph'), ('Tvr Certified', 'tvr'), ('Volkswagen Certified', 'volkswagen'), ('Volvo Certified', 'volvo'), ('Willys Certified', 'willys'), ('Yugo Certified', 'yugo')], default='Used', max_length=100, null=True, verbose_name='Car Stock Type'),
        ),
        migrations.AlterField(
            model_name='autosearch',
            name='car_year',
            field=models.CharField(blank=True, choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2000, max_length=100, null=True, verbose_name='Car Manufacturing Year'),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
