# Generated by Django 3.1.13 on 2021-08-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_auto_20210812_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosearch',
            name='car_url',
            field=models.CharField(blank=True, max_length=700, null=True, unique=True, verbose_name='Car Detail Link'),
        ),
        migrations.AlterField(
            model_name='autosearch',
            name='car_vin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Car VIN'),
        ),
    ]
