# Generated by Django 3.1.13 on 2021-08-12 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0018_auto_20210812_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='autosearch',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='car_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='autosearch',
            name='car_stock',
            field=models.CharField(blank=True, choices=[('Used', 'Used'), ('Ac_Certified', 'ac'), ('Acura_Certified', 'acura'), ('Alfa_Romeo _Certified', 'alfa romeo'), ('Allard_Certified', 'allard'), ('Amc_Certified', 'amc'), ('Am_General_Certified', 'am general'), ('American_Motors_Certified', 'american motors'), ('Ariel_Certified', 'ariel'), ('Aston_Martin_Certified', 'aston martin'), ('Auburn_Certified', 'auburn'), ('Audi_Certified', 'audi'), ('Austin_Certified', 'austin'), ('Austin_Healey_Certified', 'austin healey'), ('Avantimotors_Certified', 'avantimotors'), ('Bentley_Certified', 'bentley'), ('BMW_Certified', 'bmw'), ('Bugatti_Certified', 'bugatti'), ('Buick_Certified', 'buick'), ('Cadillac_Certified', 'cadillac'), ('Checker_Certified', 'checker'), ('Chevrolet_Certified', 'chevrolet'), ('Chrysler_Certified', 'chrysler'), ('Citroen_Certified', 'citroen'), ('Daewoo_Certified', 'daewoo'), ('Daihatsu_Certified', 'daihatsu'), ('Datsun_Certified', 'datsun'), ('Delahaye_Certified', 'delahaye'), ('Delorean_Certified', 'delorean'), ('Desoto_Certified', 'desoto'), ('Detomaso_Certified', 'detomaso'), ('Dodge_Certified', 'dodge'), ('Eagle_Certified', 'eagle'), ('Edsel_Certified', 'edsel'), ('Essex_Certified', 'essex'), ('Ferrari_Certified', 'ferrari'), ('Fiat_Certified', 'fiat'), ('Fisker_Certified', 'fisker'), ('Ford_Certified', 'ford'), ('Franklin_Certified', 'franklin'), ('Freightliner_Certified', 'freightliner'), ('Genesis_Certified', 'genesis'), ('GEO_Certified', 'geo'), ('GMC_Certified', 'gmc'), ('Hino_Certified', 'hino'), ('Honda_Certified', 'honda'), ('Hudson_Certified', 'hudson'), ('Hummer_Certified', 'hummer'), ('Hupmobile_Certified', 'hupmobile'), ('Hyundai_Certified', 'hyundai'), ('INFINITI_Certified', 'infiniti'), ('International_Certified', 'international'), ('Intlharvester_Certified', 'intlharvester'), ('Isuzu_Certified', 'isuzu'), ('Jaguar_Certified', 'jaguar'), ('Jeep_Certified', 'jeep'), ('Jensen_Certified', 'jensen'), ('Kaiser_Certified', 'kaiser'), ('Karma_Certified', 'karma'), ('Kia_Certified', 'kia'), ('Koenigsegg_Certified', 'koenigsegg'), ('Lamborghini_Certified', 'lamborghini'), ('Lancia_Certified', 'lancia'), ('Land_Rover_Certified', 'land rover'), ('Lasalle_Certified', 'lasalle'), ('Lexus_Certified', 'lexus'), ('Lincoln_Certified', 'lincoln'), ('Lotus_Certified', 'lotus'), ('Maserati_Certified', 'maserati'), ('Maybach_Certified', 'maybach'), ('Mazda_Certified', 'mazda'), ('Mclaren_Certified', 'mclaren'), ('Mercedes_Benz_Certified', 'mercedes benz'), ('Mercury_Certified', 'mercury'), ('Merkur_Certified', 'merkur'), ('MG_Certified', 'mg'), ('Mini_Certified', 'mini'), ('Mitsubishi_Certified', 'mitsubishi'), ('Morgan_Certified', 'morgan'), ('Morris_Certified', 'morris'), ('Nash_Certified', 'nash'), ('Nissan_Certified', 'nissan'), ('Oldsmobile_Certified', 'oldsmobile'), ('Opel_Certified', 'opel'), ('Packard_Certified', 'packard'), ('Pagani_Certified', 'pagani'), ('Panoz_Certified', 'panoz'), ('Peugeot_Certified', 'peugeot'), ('Plymouth_Certified', 'plymouth'), ('Polestar_Certified', 'polestar'), ('Pontiac_Certified', 'pontiac'), ('Porsche_Certified', 'porsche'), ('Qvale_Certified', 'qvale'), ('RAM_Certified', 'ram'), ('Renault_Certified', 'renault'), ('Rolls Royce_Certified', 'rollsroyce'), ('Rover_Certified', 'rover'), ('Saab_Certified', 'saab'), ('Saleen_Certified', 'saleen'), ('Saturn_Certified', 'saturn'), ('Scion_Certified', 'scion'), ('Ehelby_Certified', 'shelby'), ('Smart_Certified', 'smart'), ('Spyker_Certified', 'spyker'), ('Sterling_Certified', 'sterling'), ('Studebaker_Certified', 'studebaker'), ('Subaru_Certified', 'subaru'), ('Sunbeam_Certified', 'sunbeam'), ('Suzuki_Certified', 'suzuki'), ('Tesla_Certified', 'tesla'), ('Toyota_Certified', 'toyota'), ('Triumph_Certified', 'triumph'), ('Tvr_Certified', 'tvr'), ('Volkswagen_Certified', 'volkswagen'), ('Volvo_Certified', 'volvo'), ('Willys_Certified', 'willys'), ('Yugo_Certified', 'yugo')], default='Used', max_length=100, null=True, verbose_name='Car Stock Type'),
        ),
        migrations.CreateModel(
            name='WatchCars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('active', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchedcar', to='cars.autosearch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userwatch', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Car Watch',
                'verbose_name_plural': 'Car Watch',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
    ]
