# Generated by Django 3.1.13 on 2021-08-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_auto_20210812_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='autosearch',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
