# Generated by Django 3.1.13 on 2021-09-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0024_auto_20210904_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='autosearch',
            name='car_body',
            field=models.CharField(blank=True, choices=[('', 'all'), ('sedan', 'sedan'), ('coupe', 'coupe'), ('convertible', 'convertible'), ('wagon', 'wagon'), ('hatchback', 'hatchback'), ('passenger_van', 'passenger van'), ('suv', 'suv'), ('minivan', 'minivan'), ('pickup_truck', 'pickup truck'), ('cargo_van', 'cargo van')], default='', max_length=15, null=True, verbose_name='Car Body'),
        ),
        migrations.AddField(
            model_name='autosearch',
            name='car_door',
            field=models.CharField(blank=True, choices=[('all', 'all'), ('2', '2-3'), ('4', '4')], default='2', max_length=15, null=True, verbose_name='Car Door'),
        ),
    ]
