# Generated by Django 3.1.13 on 2021-09-05 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0025_auto_20210905_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autosearch',
            name='car_def_image',
        ),
    ]
