# Generated by Django 3.1.13 on 2021-09-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0027_auto_20210905_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosearch',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Car Title'),
        ),
    ]
