# Generated by Django 3.1.13 on 2021-09-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0029_auto_20210905_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='autosearch',
            name='special',
            field=models.BooleanField(default=False, verbose_name='Special Offer'),
        ),
        migrations.AlterField(
            model_name='autosearch',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Car Availability'),
        ),
        migrations.AlterField(
            model_name='autosearch',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured Cars'),
        ),
    ]
