# Generated by Django 3.1.13 on 2021-09-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0030_auto_20210905_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosearch',
            name='car_history',
            field=models.URLField(blank=True, max_length=700, null=True, unique=True, verbose_name='Car History Link'),
        ),
        migrations.AlterField(
            model_name='autosearch',
            name='car_url',
            field=models.CharField(blank=True, max_length=700, null=True, unique=True, verbose_name='Car Detail Link'),
        ),
        migrations.AlterField(
            model_name='autosearch',
            name='car_vin',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Car VIN'),
        ),
    ]
