# Generated by Django 3.1.13 on 2021-09-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0033_auto_20210905_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Alternative Image Upload Field'),
        ),
    ]
