# Generated by Django 3.1.13 on 2021-09-06 18:00

import autobuyfast.cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0038_auto_20210906_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=autobuyfast.cars.models.post_image, verbose_name='Upload Car Image'),
        ),
    ]
