# Generated by Django 3.1.13 on 2021-09-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0040_auto_20210906_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_url',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Alternative Image Upload Field'),
        ),
    ]
