# Generated by Django 3.1.13 on 2021-09-07 04:55

import autobuyfast.cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0042_auto_20210906_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='autosearch',
            name='car_map_location',
            field=models.URLField(blank=True, null=True, verbose_name='Paste your Google Location'),
        ),
        migrations.AddField(
            model_name='autosearch',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to=autobuyfast.cars.models.car_vid_path, verbose_name='Upload Car Video'),
        ),
    ]
