# Generated by Django 3.1.13 on 2021-09-08 02:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0043_auto_20210907_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCompare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('car_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carone', to='cars.autosearch')),
                ('car_three', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carthree', to='cars.autosearch')),
                ('car_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartwo', to='cars.autosearch')),
            ],
            options={
                'verbose_name': 'Car Compare',
                'verbose_name_plural': 'Cars Compared',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
    ]
