# Generated by Django 3.1.13 on 2021-09-08 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0044_carcompare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcompare',
            name='car_one',
            field=models.ForeignKey(default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carone', to='cars.autosearch'),
        ),
        migrations.AlterField(
            model_name='carcompare',
            name='car_three',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carthree', to='cars.autosearch'),
        ),
        migrations.AlterField(
            model_name='carcompare',
            name='car_two',
            field=models.ForeignKey(default=9, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartwo', to='cars.autosearch'),
        ),
    ]
