# Generated by Django 3.1.13 on 2021-09-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0047_savecarsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='savecarsearch',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
