# Generated by Django 3.1.13 on 2021-09-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210810_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.1, max_digits=2, null=True, verbose_name='Car Review Rating'),
        ),
    ]
