# Generated by Django 3.1.13 on 2021-08-06 19:53

import autobuyfast.users.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import model_utils.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('newsletter_notif', models.BooleanField(default=False, verbose_name='Subscribe to Newsletter?')),
                ('search_notif', models.BooleanField(default=False, verbose_name='Send Email When Saved Search is deleted?')),
                ('car_sold_notif', models.BooleanField(default=False, verbose_name='Send Email When Saved car is sold?')),
                ('car_price_notif', models.BooleanField(default=False, verbose_name='Send Email When Saved car price has been reduced?')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created', '-modified'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dealership_name', models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Company Name')),
                ('bio', tinymce.models.HTMLField(blank=True, null=True, verbose_name='What services will buyers find appealing from you?')),
                ('website', models.URLField(blank=True, null=True, unique=True, verbose_name='Website URI')),
                ('profile_display', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', help_text='Image should be squared and sized 120px X 120px', keep_meta=True, quality=64.15, size=[120, 120], upload_to=autobuyfast.users.models.profile_image)),
                ('banner_display', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', help_text='Image should be cropped and sized 1280px X 300px', keep_meta=True, quality=64.15, size=[1280, 300], upload_to=autobuyfast.users.models.banner_image)),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=500, null=True, verbose_name='City')),
                ('zipcode', models.CharField(blank=True, max_length=500, null=True, verbose_name='Zipcode')),
                ('member_since', models.DateField(default=datetime.datetime.now, verbose_name='Membership Age')),
                ('security_quest', models.CharField(choices=[('favourite actor', 'Who is your favourite actor?'), ("pet's name", "What is your pet's name?"), ('first school attended', 'What is the name of the first school attended?'), ('place of birth', 'Where is your place of birth?'), ("mother's maiden name", "What is your mother's maiden name?")], default="mother's maiden name", max_length=47, verbose_name='Security Question')),
                ('security_answer', models.CharField(blank=True, max_length=500, null=True, verbose_name='Security Answer')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealercountry', to='countries_plus.country')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-created', '-modified'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('testimony', models.CharField(blank=True, max_length=800, null=True, verbose_name='Testimony')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created', '-modified'],
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_buyer',
        ),
        migrations.AddField(
            model_name='user',
            name='has_testified',
            field=models.BooleanField(default=False, verbose_name='Has this user testified to our service?'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(default=True, verbose_name='Are you a dealer?'),
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='Dealer',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usertestimonial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertsetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='useralerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
