# Generated by Django 3.1.13 on 2021-09-02 00:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210810_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Your fullname')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Your email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Your phone')),
                ('pickup', models.DateField(null=True, verbose_name='Pickup Date')),
                ('services', models.CharField(blank=True, choices=[('International', 'International Delivery'), ('US Delivery', 'US Delivery'), ('Delivery Quote', 'Delivery Quote')], max_length=50, null=True, verbose_name='Services')),
                ('message', tinymce.models.HTMLField(help_text='Tell us more information about your shippment, where from and where to')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='search_notif',
        ),
    ]
