# Generated by Django 3.1.13 on 2021-09-04 09:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210902_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrequest',
            name='pickup',
            field=models.DateField(default=datetime.datetime(2021, 9, 4, 9, 44, 33, 999005, tzinfo=utc), null=True, verbose_name='Pickup Date'),
        ),
    ]
