# Generated by Django 3.1.13 on 2021-09-05 00:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210905_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrequest',
            name='pickup',
            field=models.DateField(default=datetime.datetime(2021, 9, 5, 0, 30, 13, 739825, tzinfo=utc), null=True, verbose_name='Pickup Date'),
        ),
    ]
