# Generated by Django 3.1.13 on 2021-09-06 12:33

import autobuyfast.users.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20210906_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrequest',
            name='pickup',
            field=models.DateField(default=datetime.datetime(2021, 9, 6, 12, 33, 53, 604492, tzinfo=utc), null=True, verbose_name='Pickup Date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='banner_display',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='Image should be cropped and sized 1280px X 300px', keep_meta=True, null=True, quality=75, size=[1280, 300], upload_to=autobuyfast.users.models.banner_image),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_display',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='Image should be squared and sized 120px X 120px', keep_meta=True, null=True, quality=75, size=[120, 120], upload_to=autobuyfast.users.models.profile_image),
        ),
    ]
