# Generated by Django 3.1.13 on 2021-09-06 14:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20210906_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured Dealers'),
        ),
        migrations.AlterField(
            model_name='carrequest',
            name='pickup',
            field=models.DateField(default=datetime.datetime(2021, 9, 6, 14, 58, 6, 98028, tzinfo=utc), null=True, verbose_name='Pickup Date'),
        ),
    ]
