# Generated by Django 3.1.13 on 2021-09-06 16:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20210906_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrequest',
            name='pickup',
            field=models.DateField(default=datetime.datetime(2021, 9, 6, 16, 56, 38, 840312, tzinfo=utc), null=True, verbose_name='Pickup Date'),
        ),
    ]
