# Generated by Django 3.1.13 on 2021-09-06 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20210906_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrequest',
            name='pickup',
            field=models.DateField(default=datetime.datetime(2021, 9, 6, 17, 30, 41, 919803, tzinfo=utc), null=True, verbose_name='Pickup Date'),
        ),
    ]
