# Generated by Django 3.1.13 on 2021-09-06 17:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20210906_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrequest',
            name='pickup',
            field=models.DateField(default=datetime.datetime(2021, 9, 6, 17, 37, 1, 123457, tzinfo=utc), null=True, verbose_name='Pickup Date'),
        ),
    ]
