# Generated by Django 3.1.13 on 2021-09-06 18:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20210906_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrequest',
            name='pickup',
            field=models.DateField(default=datetime.datetime(2021, 9, 6, 18, 0, 39, 983241, tzinfo=utc), null=True, verbose_name='Pickup Date'),
        ),
    ]
