# Generated by Django 3.1.13 on 2021-09-08 02:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20210907_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrequest',
            name='pickup',
            field=models.DateField(default=datetime.datetime(2021, 9, 8, 2, 27, 19, 722889, tzinfo=utc), null=True, verbose_name='Pickup Date'),
        ),
    ]
