# Generated by Django 3.1.13 on 2021-09-08 03:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20210908_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrequest',
            name='pickup',
            field=models.DateField(default=datetime.datetime(2021, 9, 8, 3, 57, 59, 244844, tzinfo=utc), null=True, verbose_name='Pickup Date'),
        ),
    ]
