# Generated by Django 3.1.13 on 2021-09-10 03:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20210910_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrequest',
            name='pickup',
            field=models.DateField(default=datetime.datetime(2021, 9, 10, 3, 10, 51, 854123, tzinfo=utc), null=True, verbose_name='Pickup Date'),
        ),
    ]
