# Generated by Django 3.1.13 on 2021-09-10 21:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_auto_20210910_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrequest',
            name='pickup',
            field=models.DateField(default=datetime.datetime(2021, 9, 10, 21, 0, 11, 485020, tzinfo=utc), null=True, verbose_name='Pickup Date'),
        ),
    ]
